from __future__ import annotations
from typing import Any

CAPABILITIES={
'canonical-project-state':('executable','closed normalized project state + digest'),
'2d-procedural-shapes':('rendered','rectangles/circles render to exact PPM'),
'procedural-particles':('rendered','seeded deterministic particle field'),
'transform-animation':('rendered','integer scalar/from-to/keyframe tracks'),
'multi-keyframe-animation':('rendered','ordered integer keyframe curves'),
'camera-animation':('rendered','camera x/y/zoom sampled into frame state'),
'image-sprite-import':('external-boundary','native PNG is owned; other common image formats remain optional Pillow compatibility boundaries with source/conformed evidence'),
'native-png-import':('tested','8-bit non-interlaced grayscale/RGB/gray-alpha/RGBA PNG uses native CRC + zlib/filter decoding and renders without Pillow'),
'video-clip-import':('external-boundary','input digest + FFmpeg-conformed frame evidence'),
'video-time-remap':('rendered','speed/reverse/freeze/source-frame selection'),
'video-compositor':('rendered','normal/add/multiply/screen, opacity, rotation, wipes'),
'masks-chroma':('rendered','image masks and chroma threshold in compositor'),
'text-rendering':('rendered','native 5x7 fallback plus supplied-font boundary'),
'unicode-font-shaping':('external-boundary','supplied font digest + optional Pillow/FreeType runtime evidence'),
'captions-subtitles':('rendered','burned captions + exact WebVTT export'),
'procedural-tone-audio':('rendered','48k tone synthesis'),
'external-audio-import':('external-boundary','native PCM WAV is owned; other audio formats remain FFmpeg compatibility boundaries with source/PCM receipts'),
'native-wav-import':('tested','uncompressed 8/16/24/32-bit integer PCM WAV decodes and deterministically resamples without FFmpeg'),
'audio-mixing':('rendered','timeline mixing with gain automation'),
'stereo-pan':('rendered','deterministic per-event pan/gain into stereo WAV'),
'speech-synthesis':('tested','native deterministic speech is default for v0.5 projects; legacy eSpeak remains optional'),
'native-speech-synthesis':('tested','native fixed-point/table oscillator + rule/phoneme formant synthesis emits PCM without a speech engine'),
'speech-phoneme-state':('tested','text expands into inspectable pronunciation/phoneme timing state with exact digest lineage'),
'speech-repeat-verification':('tested','same text/voice/rate reproduces the same native PCM and speech receipt'),
'human-intelligible-native-speech':('gap','native waveform path is real but human listening feedback found the v0.8 proof unintelligible as words'),
'external-speech-adapter':('external-boundary','legacy/explicit eSpeak path remains available and receipted when selected'),
'effect-organs':('executable','detached effect forge/adoption path'),
'pixel-program-effects':('executable','bounded effect stack language, no eval'),
'3d-scene-rendering':('rendered','fixed-point primitive/mesh projection + triangle raster'),
'mesh-import':('rendered','native OBJ v/vt/f parser'),
'uv-texture-mapping':('rendered','nearest/bilinear UV texture sampling on triangles under explicit realization contract'),
'deterministic-supersampling':('tested','adaptive realization can render transient 2x/3x internal samples and box-resolve to unchanged canonical canvas'),
'visual-fidelity-scaling':('tested','machine tiers vary internal sampling and texture filtering separately from scene/detail density'),
'cast-shadows':('rendered','deterministic directional screen-space shadow projection'),
'skeletal-animation':('rendered','hierarchical rig2d runtime'),
'weighted-3d-skinning':('tested','explicit 3D bone rig + 1..4 milli-weight influences deform OBJ vertices before projection; weights fail closed unless each weighted vertex sums to 1000'),
'weighted-skinning-receipts':('tested','frame state exposes stable skin-state identity and per-frame bone-pose digest, weighted vertex count, bone count and algorithm identity'),
'morph-target-animation':('rendered','vertex interpolation between compatible meshes'),
'nested-compositions':('rendered','FrameState project as visual child with child lineage'),
'nested-audio':('rendered','child FrameState audio can enter parent mix with lineage'),
'shot-plan-compiler':('executable','relative shots compile into one canonical project'),
'creative-brief-compiler':('executable','high-level beats/style/media compile into canonical shot plan and project'),
'shot-recipe-organs':('executable','detached reusable shot templates can be replay-tested and adopted behind four-root + recovery gate'),
'shot-manager':('executable','markers derive shot spans'),
'storyboard-generator':('rendered','representative actual rendered frames + digest lineage'),
'render-queue':('executable','batch project rendering with queue receipt'),
'frame-analysis':('executable','non-mutating frame color/delta analysis and cut proposals'),
'mp4-assembly':('external-boundary','FFmpeg profile encode, version/output digest'),
'repeat-verification':('tested','second full render compares project/media/frame/audio truth'),
'mechanical-video-review':('executable','bounded framing/audio/camera checks'),
'rehearsal-iteration':('tested','candidate render -> mechanical evidence -> bounded delta -> replay -> compare -> accept/hold loop'),
'deterministic-quality-loop':('tested','quality path can iterate evidence-backed construction before final output without hidden artistic scoring'),
'bounded-prompt-compiler':('tested','prompt text compiles into explicit native operations with a prompt-plan receipt'),
'style-prompt-bundles':('tested','versioned cinematic/cleaner/documentary/warm/cool-color bundles map to inspectable state operations'),
'direct-edit-prompts':('tested','bounded title/audio/caption/footage instructions compile into native state deltas'),
'prompt-ambiguity-hold':('tested','ambiguous semantic terms remain visible and do not silently mutate project state'),
'prompt-rehearsal-bridge':('tested','prompt-applied candidate state can enter deterministic rehearsal before final render'),
'prompt-repeat-verification':('tested','same project + same prompt produces stable plan/candidate state and repeat-verifiable final output'),
'daily-recovery':('executable','whole-body snapshot before supported live adoption'),
'machine-capability-probe':('tested','bounded host probe records cores/memory and executable dependency/backend facts without person/device identity fingerprinting'),
'adaptive-realization-planner':('tested','canonical project + machine capabilities + user policy compile into deterministic render contract'),
'expression-degradation-receipts':('tested','particle/shadow/effect reductions are explicit deltas while canonical project digest remains unchanged'),
'user-realization-policy':('tested','exact/adaptive/performance-first policy and fidelity/detail bounds outrank automatic optimization'),
'adaptive-render-repeat-verification':('tested','same canonical state + machine capability state + policy reproduces the same realization contract, fidelity choice and native frames'),
'local-creation-studio':('tested','loopback-only dependency-free Studio edits canonical project state and retains raw canonical JSON as universal state access'),
'actual-renderer-studio-preview':('tested','Studio preview calls the native FrameState render_frame path in exact/adaptive modes and returns digest-bound frame state'),
'atomic-canonical-save':('tested','Studio normalizes project state and saves through fsync + atomic replace without implicit render-to-project mutation'),
'studio-media-intake':('tested','browser-selected assets are copied into project-local assets with sanitized names, source digests, and explicit canonical media/layer/audio state'),
'dependency-free-core-package':('tested','CI wheel installs and packaged CLI/Studio/resume/parallel/portable entry points load without Pillow installed; optional media/font compatibility remains explicit'),
'portable-desktop-application':('tested','single-file frozen FrameState application embeds Python/native core + Studio resources and smoke-passes on Linux, Windows and macOS'),
'portable-build-receipts':('tested','three-OS portable workflow records SHA-256, size, runner platform and Python version beside each frozen application artifact'),
'parallel-frame-render-backend':('tested','two or more OS processes render independent canonical frames and the parent admits verified output in canonical order; manifest matches the single-process renderer exactly'),
'portable-parallel-render':('tested','the one-file frozen FrameState application completes a two-worker native render on Linux, Windows and macOS'),
'accelerated-execution-backend':('tested','FrameState has a dependency-free multi-process frame execution backend that can use additional CPU cores without changing frame truth'),
'crash-resumable-native-render':('tested','checkpoint-admitted native frame prefix can resume to the same manifest as uninterrupted render_project output'),
'resume-identity-gate':('tested','project/media/realization drift and corrupt admitted frame bytes fail closed; unadmitted tail bytes are discarded'),
'render-disk-budget-gate':('tested','resumable renderer conservatively checks remaining native frame storage plus reserve before continuing'),
'strict-canonical-json-admission':('tested','canonical JSON rejects non-finite state instead of emitting non-portable JSON'),
'media-output-confinement':('tested','portable media ids and symlink-aware output guards keep generated media beneath the selected render root'),
'forge-single-writer-publication':('tested','effect and recipe adoption use create-only single-writer publication with concurrent losers held'),
'render-checkpoint-integrity':('tested','resumable checkpoint admission binds persisted progress to checkpoint and frame evidence before continuation'),
'renderer-neutral-visual-state-bridge':('tested','pinned Universal Creation visual-state evidence maps only bounded realization direction; unsupported state remains held'),
'echoworld-replay-visual-bridge':('tested','caller-pinned EchoWorld replay evidence is admitted and rendered through a non-authoritative deterministic projection'),
'caller-pinned-render-output-verification':('tested','read-only local admission verifies caller-pinned receipt/project identity plus manifests, frames, audio, captions and realization evidence'),
'cross-python-regression':('tested','complete regression tree is exercised on CPython 3.11, 3.12 and 3.13 in GitHub Actions'),
'hardware-gpu-raster-backend':('gap','physical GPU raster execution is not required for v1; cpu-software remains the pixel-reference path and cpu-parallel is the tested accelerated execution path'),
'natural-language-directing':('gap','bounded direct/style prompts are native, but unrestricted free-form semantic language still requires an explicit translator/interpretation boundary'),
'arbitrary-self-modification':('gap','growth remains bounded; no arbitrary self-write authority'),
}

def capability_summary()->dict[str,Any]:
    return {'schema':'axm.framestate.capability-map/v0.16','capabilities':{k:{'status':v[0],'evidence':v[1]} for k,v in CAPABILITIES.items()}}

def analyze_requirements(required:list[str])->dict[str,Any]:
    rows=[];ready=True
    for cap in required:
        if cap not in CAPABILITIES: rows.append({'capability':cap,'status':'unknown','evidence':'not present in current capability map'});ready=False
        else:
            s,e=CAPABILITIES[cap];rows.append({'capability':cap,'status':s,'evidence':e});ready &= s!='gap'
    return {'ready':bool(ready),'requirements':rows,'smallest_visible_gaps':[r['capability'] for r in rows if r['status'] in {'gap','unknown'}]}
